name: Deploy

on:
  push:
    branches:
      - master
      - source
  pull_request:
    branches:
      - master
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
    - name: Enable bundler cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install deps
      run: |
        gem install bundler 
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=source" >> "$GITHUB_OUTPUT"
          echo "NO_PUSH=--no-push" >> "$GITHUB_OUTPUT"
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=source" >> "$GITHUB_OUTPUT"
        fi
        if [[ ${{ github.repository }} = *.github.io ]]; then # user/org repo
          echo "DEPLOY_BRANCH=master" >> "$GITHUB_OUTPUT"
        else
          echo "DEPLOY_BRANCH=gh-pages" >> "$GITHUB_OUTPUT"
        fi
    - name: Deploy website 
      run:  yes | bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }}
                    --src ${{ steps.setup.outputs.SRC_BRANCH }}
                    --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
